### ISSUE TITLE
Crashes on setup test

### ISSUE THREAD

**Issue by TonyHeadband** [techartorg/bqt#118]
Blender crashes when testing a fresh new install, on Blender 3.6.1
`import PySide2.QtWidgets
a = PySide2.QtWidgets.QMainWindow() # Crashes here
a.show()`

I've found out that from the demo files that this line returns nothing
`QtWidgets.QApplication.instance()`
so this line fails
`main_window = QtWidgets.QApplication.instance().blender_widget`

**Comment by hannesdelbeke** [comment]
Can you go to your blender install folder.
And run the blender log bat file?
Then it should open the log after it crashes.
Please share the log here

**Comment by TonyHeadband** [comment]
> qt.qpa.window: SetProcessDpiAwarenessContext() failed: The operation completed successfully.
> Qt's default DPI awareness context is DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2. If you know what you are doing, you can overwrite this default using qt.conf (https://doc.qt.io/qt-6/highdpi.html#configuring-windows).
> I1227 11:33:40.928444 39584 device.cpp:32] CUEW initialization succeeded
> I1227 11:33:40.929445 39584 device.cpp:34] Found precompiled kernels
> I1227 11:33:40.940960 39584 device.cpp:60] HIPEW initialization failed: Error opening HIP dynamic library
> QWidget: Must construct a QApplication before a QWidget

This is the blender_debug_output.txt

**Comment by hannesdelbeke** [comment]
It seems like you say. This returns None because the bqt setup failed. Crashing blender when doing widget.show()
```python
QtWidgets.QApplication.instance()
```
Did you paste the whole log? I want to see the error that tells me why instance setup fails

**Comment by TonyHeadband** [comment]
That's the whole file, I can send the system info one, but the last line is
`bqt (version: (1, 4, 2), path: M:\Pipeline\tools\Blender\scripts\addons\bqt\__init__.py)`
which seems fine and I can see Blender Qt wrapping blender

**Comment by hannesdelbeke** [comment]
If you see blender wrapped in bqt, it's weird instance returns none.
Maybe it's using pyside6 instead of 2.
I recently updated the default to 6 i believe.

**Comment by SpicyMelonYT** [comment]
Any news about this? I am also getting the QApplication.instance() is None thing. Its odd since the addon seems to work in the sense that the blender instance looks like it gets reparented to something as the header of the file changes to the title "Blender Qt"

I am using the 1.42 addon for blender 4.0. Given that it reparents the window I would think this is not a 4.0 issue.

Also in my blender install folder I see no log bat file?

**Comment by coconutoctopus** [comment]
Hello! We, too, have this same issue. Is it a setup thing?

**Comment by hannesdelbeke** [comment]
hi i ll have a look

> Also in my blender install folder I see no log bat file?
![image](https://github.com/techartorg/bqt/assets/3758308/bc54a8b4-e211-433e-9e30-29bf40ea261c)

**Comment by hannesdelbeke** [comment]
how did both of you install bqt?

**Comment by hannesdelbeke** [comment]
I updated all demo files to `PySide6`

If you had `PySide2` installed, the old demo file would work, but return None for the `QApplication instance`
because no `PySide2 QApplication` exists, only a `PySide6 QApplication`.
This is why you can see Blender being wrapped in Qt

The old code the original poster tried to run, will return `None`
```
import PySide2.QtWidgets 
a = PySide2.QtWidgets.QMainWindow() 
# Crashes here a.show()

# I've found out that from the demo files that this line returns nothing
QtWidgets.QApplication.instance()
```

closing this, please reopen if you still run into issues

**Comment by coconutoctopus** [comment]
Ah yes was about to report back that switching to Pyside 6 fixed it for me. Thank you for digging into it!
