### ISSUE TITLE
figure out why bqt works without event loop

### ISSUE THREAD

**Issue by hannesdelbeke** [techartorg/bqt#74]
when using qt without bqt, creating a `QApplication` and `exec` it in Blender freezes Blender input, untill we close the widget.
You can test this with following pseudo code
```python
app = QApplication()
w = QWidget()
w.show()
app._exec()
```

to solve this, we usually create an event loop in QT scripts.

At some point in refactoring BQT, I removed the event loop since it wasnt needed to prevent blender from freezing. 
But I don't understand why. It would be good to figure out what part of the code in BQT prevents Blender from freezing.

pointed out in https://github.com/techartorg/bqt/issues/70, where we look at adding bqt support to linux.

**Comment by hannesdelbeke** [comment]
actual test code
```python
def show():
    app = QtWidgets.QApplication.instance()
    
    exec = False
    if not app:
        exec = True
        app = QtWidgets.QApplication()

    window = QWidget()
    window.show()

    if exec:
        app.exec_()

    return window
```

this freezes blender the first time i run it.
but when i close the widget and run it a second time it's fine.
likely related to fact that we don't exec again in the show method. and use the QApp instance instead

**Comment by bob-white** [comment]
This is _VERY_ high level, and very handwavy, but hopefully this helps.

So what `exec_` is doing under the hood, is basically
```
while True:
    msg = get_message_from_os()
    if msg in stuff_we_care_about:
        process_message(msg)
    sleep(0.001)
```
Where it's listening for the various OS events/messages, and then processing the important ones and otherwise trying to do a minimum amount of work to maintain the illusion of realtime interaction.

So why does this freeze blender? Well because it has its own similar loop, and when you run this code inside that loop, it never gets to continue until the QApplication is closed.

Why does this work in blender? Well that's because OS native message handling is pretty universally understood, and when the user interacts with a Qt widget, those messages get processed by blender's loop, and when messages come in from the OS aimed at Qt widget, the widget IDs are part of that message, and the message processing shunts them to the correct part of the UI.

**Comment by hannesdelbeke** [comment]
thanks for this breakdown 🙏

> So why does this freeze blender? Well because it has its own similar loop, and when you run this code inside that loop, it never gets to continue until the QApplication is closed.

It  makes sense that Blender is blocked, since QApp has it's own infinite while loop to process events.

What I don't get is why it starts working after we close the widget. Since we close the widget, not the QApplication.
When I check after closing the widget, `QtWidgets.QApplication.instance()` doesn't return `None`, implying it stays in active.

I would have expected that closing the widget closes the widget, but continues the QApps while loop. Processing it's qt events etc.

**Comment by bob-white** [comment]
This is wild speculation, but my guess would be that because blender is the primary owner of the process, it is stopping the QApplication from fully exiting. So while its internal message loop stops after you close the last visible widget, the application itself remains.
Hence why calling `QApplication.instance()` returns an instance, and much like bqt, the message passing routes through blender's message loop.

**Comment by hannesdelbeke** [comment]
- noticed when docking a widget to blender qt window, it freezes untill you move the mouse. implying that the qt repaint / eventloop is not properly hooked up.
- qt timers however runs smoothly when mouse is not moving.

**Comment by hannesdelbeke** [comment]
```python
from PySide2 import QtCore, QtWidgets
app = QtWidgets.QApplication([])
QtCore.QTimer.singleShot(1, app.quit)  # Schedule a call to app.quit() after 1 ms
app.exec_()  # Start the event loop
```
running this before doing qt stuff without bqt also makes blender responsive.
i assume bqt somehow triggers the quit method from the qapp during it's setup / window wrap.

**Comment by hannesdelbeke** [comment]
i had similar behaviour when testing python in unity. with pyblish. it should have blocked, but it didn't the second time

**Comment by bob-white** [comment]
It might be worth putting some prints in https://github.com/techartorg/bqt/blob/be84d0b2de6763d2ff2d3b4557cae31475ed8ef2/bqt/blender_applications/blender_application.py#L180 to see what events are actually being passed to the QApplication.
An even more noisy event stream can be hooked into using https://doc.qt.io/qt-5/qcoreapplication.html#installNativeEventFilter, which again might also be helpful.

Might be able to identify if something is swallowing the quit/close events (or if they're even firing at all)

**Comment by hannesdelbeke** [comment]
nice, tried that. close event doesn't trigger on startup./
it does trigger when i open a widget and close it.

**Comment by hannesdelbeke** [comment]
event types on startup 
![image](https://github.com/techartorg/bqt/assets/3758308/8d12bfba-c397-4a76-89b5-f771ed9ccb32)

**Comment by hannesdelbeke** [comment]
when modifying bqt code to load a normal QApplication on startup, Blender freezes as expected
```python
    global app
    app = QApplication()
    app.exec_()
    # _create_global_app()  # this is what it normall does, creating our custom BlenderQApplication
```

**Comment by hannesdelbeke** [comment]
seems mystery is solved. only need to check on other OSes, since someone reported it freezes on linux but they might have run exec. haven't seen their code.
